name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest # 指定运行环境 最新的 Ubuntu 版本

    steps:
      # Step 1: Checkout代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v4

      # Step 3: 安装依赖
      - name: Install dependencies
        run: npm install

      # Step 4: 运行测试
      - name: Run ci
        run: npm ci

      
