name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macOS-latest # 指定运行环境

    steps:
      # Step 1: Checkout代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v4

      # Step 3: 安装 pnpm
      - name: Install pnpm
        run: |
          npm install -g pnpm

      # Step 4: 安装依赖
      - name: Install dependencies
        run: |
          pnpm install
          pnpm add -D electron@^12

      # Step 5: Electron 需要一个虚拟显示器
      - name: Setup virtual display
        run: |
          Xvfb :99 -screen 0 1024x768x24 &
          export DISPLAY=:99

      # Step 6: 运行测试
      - name: Run ci
        run: npm run ci -- --testTimeout=300000

      
